apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::483884450788:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-DHtyRtRkb2Vv
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::483884450788:role/UdacityFlaskDeployCBKubectlRole
      username: build    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-22T22:47:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1317"
  uid: ad221c4b-0dba-4ae9-8863-106d8ea7aad0
